---
# Foodtruck v1
# :: Spin up EKS, Third Party tools, configure.

- name: (CHECK FOR PERMITS) Pre-flight check
  hosts: localhost
  connection: local
  tags:
    - always

- name: (SET UP THE FOODTRUCK) Spin Up IaC
  import_playbook: foodtruck-v1-iacInit.yml

